"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 00:04:57.647762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('developer', sa.String(length=500), nullable=True),
    sa.Column('developer_id', sa.String(length=255), nullable=True),
    sa.Column('genre_id', sa.String(length=64), nullable=True),
    sa.Column('icon_url', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_rating', sa.String(length=100), nullable=True),
    sa.Column('released', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('free', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('contains_ads', sa.Boolean(), nullable=False),
    sa.Column('offers_iap', sa.Boolean(), nullable=False),
    sa.Column('pre_register', sa.Boolean(), nullable=False),
    sa.Column('real_installs', sa.BigInteger(), nullable=True),
    sa.Column('min_installs', sa.BigInteger(), nullable=True),
    sa.Column('ratings', sa.BigInteger(), nullable=True),
    sa.Column('reviews', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_game', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tracked', sa.Boolean(), nullable=False),
    sa.Column('discovered_via', sa.String(length=50), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('details_at', sa.DateTime(), nullable=True),
    sa.Column('last_charted', sa.Date(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('similar_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('app_id')
    )
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apps_developer_id'), ['developer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_genre_id'), ['genre_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_is_game'), ['is_game'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_released'), ['released'], unique=False)
        batch_op.create_index(batch_op.f('ix_apps_tracked'), ['tracked'], unique=False)

    op.create_table('brand_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'pattern')
    )
    op.create_table('chart_daily',
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('collection', sa.String(length=32), nullable=False),
    sa.Column('n_countries', sa.Integer(), nullable=False),
    sa.Column('best_rank', sa.Integer(), nullable=True),
    sa.Column('best_country', sa.String(length=8), nullable=True),
    sa.Column('best_category', sa.String(length=64), nullable=True),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('app_id', 'date', 'collection')
    )
    with op.batch_alter_table('chart_daily', schema=None) as batch_op:
        batch_op.create_index('ix_chart_daily_date_coll', ['date', 'collection'], unique=False)

    op.create_table('developers',
    sa.Column('developer_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('app_ids', sa.JSON(), nullable=False),
    sa.Column('app_count', sa.Integer(), nullable=False),
    sa.Column('max_installs', sa.BigInteger(), nullable=True),
    sa.Column('total_installs', sa.BigInteger(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('developer_id')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job'), ['job'], unique=False)

    op.create_table('keyword_seeds',
    sa.Column('seed', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('expanded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seed', 'lang', 'country')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('seed', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('suggest_prefix_len', sa.Integer(), nullable=True),
    sa.Column('suggest_rank', sa.Integer(), nullable=True),
    sa.Column('demand', sa.Float(), nullable=False),
    sa.Column('competition', sa.Float(), nullable=True),
    sa.Column('opportunity', sa.Float(), nullable=True),
    sa.Column('top_median_installs', sa.BigInteger(), nullable=True),
    sa.Column('top_avg_rating', sa.Float(), nullable=True),
    sa.Column('young_share', sa.Float(), nullable=True),
    sa.Column('young_best_installs', sa.BigInteger(), nullable=True),
    sa.Column('brand_share', sa.Float(), nullable=True),
    sa.Column('title_match_share', sa.Float(), nullable=True),
    sa.Column('top_apps', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term', 'lang', 'country')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_analyzed_at'), ['analyzed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_keywords_demand'), ['demand'], unique=False)
        batch_op.create_index(batch_op.f('ix_keywords_opportunity'), ['opportunity'], unique=False)

    op.create_table('score_history',
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('v7', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('app_id', 'date')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_metrics',
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('installs', sa.BigInteger(), nullable=True),
    sa.Column('v7', sa.Float(), nullable=True),
    sa.Column('v7_prev', sa.Float(), nullable=True),
    sa.Column('accel', sa.Float(), nullable=True),
    sa.Column('v_life', sa.Float(), nullable=True),
    sa.Column('ratings_v7', sa.Float(), nullable=True),
    sa.Column('new_countries', sa.Integer(), nullable=False),
    sa.Column('top_countries', sa.Integer(), nullable=False),
    sa.Column('trending_countries', sa.Integer(), nullable=False),
    sa.Column('grossing_countries', sa.Integer(), nullable=False),
    sa.Column('breadth_delta7', sa.Integer(), nullable=False),
    sa.Column('best_rank', sa.Integer(), nullable=True),
    sa.Column('search_visibility', sa.Float(), nullable=False),
    sa.Column('search_keywords', sa.Integer(), nullable=False),
    sa.Column('brand_flags', sa.JSON(), nullable=False),
    sa.Column('flag_major', sa.Boolean(), nullable=False),
    sa.Column('flag_hc_publisher', sa.Boolean(), nullable=False),
    sa.Column('flag_franchise', sa.Boolean(), nullable=False),
    sa.Column('flag_big_dev', sa.Boolean(), nullable=False),
    sa.Column('flag_big_portfolio', sa.Boolean(), nullable=False),
    sa.Column('dev_max_installs', sa.BigInteger(), nullable=True),
    sa.Column('dev_app_count', sa.Integer(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('score_parts', sa.JSON(), nullable=False),
    sa.Column('spark', sa.JSON(), nullable=False),
    sa.Column('data_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.app_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_id')
    )
    with op.batch_alter_table('game_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_metrics_age_days'), ['age_days'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_metrics_trend_score'), ['trend_score'], unique=False)

    op.create_table('invites',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('keyword_ranks',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('keyword_id', 'app_id')
    )
    with op.batch_alter_table('keyword_ranks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_ranks_app_id'), ['app_id'], unique=False)

    op.create_table('marks',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'app_id')
    )
    op.create_table('saved_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_views_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('snapshots',
    sa.Column('app_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('real_installs', sa.BigInteger(), nullable=True),
    sa.Column('ratings', sa.BigInteger(), nullable=True),
    sa.Column('reviews', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.app_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('app_id', 'date')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('snapshots')
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_views_workspace_id'))

    op.drop_table('saved_views')
    op.drop_table('marks')
    with op.batch_alter_table('keyword_ranks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_ranks_app_id'))

    op.drop_table('keyword_ranks')
    op.drop_table('invites')
    with op.batch_alter_table('game_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_metrics_trend_score'))
        batch_op.drop_index(batch_op.f('ix_game_metrics_age_days'))

    op.drop_table('game_metrics')
    op.drop_table('workspaces')
    op.drop_table('score_history')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_opportunity'))
        batch_op.drop_index(batch_op.f('ix_keywords_demand'))
        batch_op.drop_index(batch_op.f('ix_keywords_analyzed_at'))

    op.drop_table('keywords')
    op.drop_table('keyword_seeds')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_job'))

    op.drop_table('job_runs')
    op.drop_table('developers')
    with op.batch_alter_table('chart_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_chart_daily_date_coll')

    op.drop_table('chart_daily')
    op.drop_table('brand_rules')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apps_tracked'))
        batch_op.drop_index(batch_op.f('ix_apps_released'))
        batch_op.drop_index(batch_op.f('ix_apps_is_game'))
        batch_op.drop_index(batch_op.f('ix_apps_genre_id'))
        batch_op.drop_index(batch_op.f('ix_apps_developer_id'))

    op.drop_table('apps')
    # ### end Alembic commands ###
