"""revivals hidden gems keyword markets

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 14:19:07.333206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_reason', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('last_trending', sa.Date(), nullable=True))

    with op.batch_alter_table('game_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revival', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('hidden_gem', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('chart_countries_any', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_game_metrics_hidden_gem'), ['hidden_gem'], unique=False)

    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_share', sa.Float(), nullable=True))

    # Games already tracked were all young or pre-registration ones
    op.execute("UPDATE apps SET track_reason = CASE WHEN pre_register THEN 'prereg' ELSE 'young' END "
               "WHERE tracked AND track_reason IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_column('games_share')

    with op.batch_alter_table('game_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_metrics_hidden_gem'))
        batch_op.drop_column('chart_countries_any')
        batch_op.drop_column('hidden_gem')
        batch_op.drop_column('revival')

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('last_trending')
        batch_op.drop_column('track_reason')

    # ### end Alembic commands ###
