"""cash games flag

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-25 19:28:27.523495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_cash', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_metrics', schema=None) as batch_op:
        batch_op.drop_column('flag_cash')

    # ### end Alembic commands ###
